### PR TITLE
Fallback strategy when `haven` fails to read an ESS file

### PR DESCRIPTION
**Pull request by briatte**
This PR makes `essurvey` use `foreign::read.spss(to.data.frame = TRUE, stringsAsFactors = FALSE)` when `haven::read_sav` or `haven::read_por` fail to read an ESS file.

## Description

The `read_format_data` function has been moved to its own script, and now works in two steps:

1. It tries to read whatever the user has downloaded with `haven`.
2. If that fails, it falls back onto `foreign` to read the file, and issues a warning.

## Related Issue

Discussed in #9 with relation to SDDF files.

## Examples

```
> x <- import_sddf_country("France", 1)
Downloading ESS1
  |=======================================================================================| 100%
Invalid time string (length=8): 0-------
Warning in FUN(X[[i]], ...) :
  Some data had to be read with the `foreign` package rather than with the `haven` package.
Please report the issue at https://github.com/ropensci/essurvey/issues
```

```
> x <- import_all_sddf_cntrounds("France")
Downloading ESS1
  |=======================================================================================| 100%
Downloading ESS2
  |=======================================================================================| 100%
Downloading ESS3
  |=======================================================================================| 100%
Downloading ESS4
  |=======================================================================================| 100%
Downloading ESS5
  |=======================================================================================| 100%
Downloading ESS6
  |=======================================================================================| 100%
Invalid time string (length=8): 0-------
Warning in FUN(X[[i]], ...) :
  Some data had to be read with the `foreign` package rather than with the `haven` package.
Please report the issue at https://github.com/ropensci/essurvey/issues
Invalid time string (length=8): 0-------
Warning in FUN(X[[i]], ...) :
  Some data had to be read with the `foreign` package rather than with the `haven` package.
Please report the issue at https://github.com/ropensci/essurvey/issues
Invalid time string (length=8): 0-------
Warning in FUN(X[[i]], ...) :
  Some data had to be read with the `foreign` package rather than with the `haven` package.
Please report the issue at https://github.com/ropensci/essurvey/issues
```

### CODE REVIEW

**Comment by cimentadaj** [comment]
@briatte really clean PR, I understood right away. We're still missing that the `foreign` result is also a `tibble` with `labelled` classes. This would break consistency across functions. I need to check whether the SDDF files have at some point labels in any of the variables because we would want to bring that as well (`haven` does but not sure about `foreign`). I'll check that, and if it doesn't bring any labels, I think using `foreign` related functions should be fine. Also, feel free to add yourself as a contributor in the DESCRIPTION.

Ignore the appveyor and Travis failing for now, this is a problem related to the environmental variable that has the ESS email.

**Comment by briatte** [comment]
@cimentadaj Thanks!

I've added myself to the DESCRIPTION, and also fixed some crucial stuff in the code:

- `country_url_sddf` did not take the `format` argument into account, so all files were downloading in Stata format :) This is now fixed.
- for some reason, the first `switch` function was using `haven::read_spss` to read POR files. I changed that to `haven::read_por`.

I've also included a one-liner to enforce lower case variable names. This creates a dependency on `tibble`, but that's alright since `haven` imports `tibble`.

Here are two `str` results for SDDF files read with `foreign` and with `haven` respectively:

```
# read with `foreign`
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1968 obs. of  6 variables:
 $ cntry   : chr  "FR" "FR" "FR" "FR" ...
  ..- attr(*, "label")= chr " "
  ..- attr(*, "format.spss")= chr "A2"
  ..- attr(*, "display_width")= int 0
 $ idno    : num  4 6 10 12 13 14 17 25 26 30 ...
  ..- attr(*, "label")= chr " "
  ..- attr(*, "format.spss")= chr "F9.0"
  ..- attr(*, "display_width")= int 0
 $ psu     : num  1034 1034 1034 1034 1034 ...
  ..- attr(*, "label")= chr " "
  ..- attr(*, "format.spss")= chr "F9.0"
  ..- attr(*, "display_width")= int 0
 $ samppoin: num  NA NA NA NA NA NA NA NA NA NA ...
  ..- attr(*, "label")= chr " "
  ..- attr(*, "format.spss")= chr "F5.0"
  ..- attr(*, "display_width")= int 0
 $ stratify: chr  "0" "0" "0" "0" ...
  ..- attr(*, "label")= chr " "
  ..- attr(*, "format.spss")= chr "A30"
  ..- attr(*, "display_width")= int 0
 $ prob    : num  Inf Inf Inf Inf Inf ...
  ..- attr(*, "label")= chr " "
  ..- attr(*, "format.spss")= chr "F14.12"
  ..- attr(*, "display_width")= int 0
```

```
# read with `haven`
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1503 obs. of  6 variables:
 $ idno    : num  10001 10002 10003 10004 10005 ...
 $ cntry   : chr  "FR" "FR" "FR" "FR" ...
 $ psu     : num  130 401 108 711 102 404 623 908 909 608 ...
 $ samppoin: num  NA NA NA NA NA NA NA NA NA NA ...
 $ stratify: chr  "        " "        " "        " "        " ...
 $ prob    : num  1.65e-05 8.24e-07 1.65e-05 7.19e-06 5.06e-07 ...
 - attr(*, "variable.labels")= Named chr  " " " " " " " " ...
  ..- attr(*, "names")= chr  "IDNO" "CNTRY" "PSU" "SAMPPOIN" ...
```

Let me know if you want me to deal with that and add more to this PR.

**Comment by cimentadaj** [comment]
I cloned your repo and tested a few things. Below are my comments:

* `devtools::check` runs OK
* I downloaded all SDDF rounds and checked that none have `haven_labelled` classes so we should be OK:

```r
library(purrr)
library(essurvey)

safe_sddf <- safely(import_all_sddf_cntrounds)
all_cnt <- map(show_countries(), safe_sddf)
transposed_cnt <- transpose(all_cnt)
named_cnt <- set_names(transposed_cnt$result, show_countries())
# Is there a haven labelled class in any of the columns?
map_lgl(named_cnt, ~ any(map_lgl(.x, ~ haven::is.labelled(.x))))
```

* We still need to add a tests for the specific cases that you've fixed with this PR. Can you add them? The tests are in the file `test-country.R` in the tests folder. What I would do is just copy the template from one of the tests of the SDDF files (for example, the one with "import_sddf_country for one/many rounds from rounds 1:4") and apply to all rounds in one country that we know has to be used using `foreign`.  Maybe do the same test for two or three countries which also exhibit the same 'foreign' problem, just to be sure. Also, we need some specific tests that check that the warning message is issued.

* I'm not entirely sure about the warning message. I think it'd be more specific if we specify the country-round for easier debugging when an issue is raised: 'Round N of country N  had to be read with the `foreign` package rather than with the `haven` package. Please report any issues at https://github.com/ropensci/essurvey/issues'

Good job by the way! The PR has been really easy to understand and adds quite a fix to `essurvey`.

**Comment by cimentadaj** [comment]
@briatte, I added some tests for your funcionality + added some more elaborate messages for using foreign. 

I was experiencing some very weird stuff while running the tests for the package locally. Sometimes reading SDDF data for France in rounds `1:3` was successfully being read from `haven` (because no `foreign` message was printed) but when running it from `devtools::check()` sometimes it failed. Moreover, all of a sudden I started getting the `foreign` package usage warning also for Spain and Slovenia, but that wasn't present neither when I started writing these commits nor when we did the tests in https://github.com/ropensci/essurvey/issues/9. Maybe I'm crazy but that threw me off. I had two hunches on where this might be coming from.

1) ESS is playing around with the `.por` or `.sav` files, which I find it very unlikely.
2) I though I had the development `haven` version and that might've messed something up but I have the latest CRAN version (2.1.1)

Can you try running `devtools::check()` on your side with the new commits to check what happens?

Should be fine with:
```r
Sys.setenv(NOT_CRAN = "true")
devtools::check(env_vars = c("ess_email" = "cimentadaj@gmail.com"))
```

**Comment by cimentadaj** [comment]
@briatte, I think that for some reason I had some package mismatch with my previous `essurvey` install and everything was messed up. Fixed it now and everything seems to work. `devtools::check()` passes locally so I'll merge it.

Thanks a lot for you work! This takes us really close to wrapping up SDDF download in `essurvey`.

**Comment by cimentadaj** [comment]
I'll make sure the tests pass in Travis now. This was due to the fact that there is a hidden environmental variable in the master branch from the `ropensci` repo.

**Comment by briatte** [comment]
Hi @cimentadaj -- Thanks for the merge, as well as for the code review and improvements.

**Pull request merged**
